# Generated by Django 3.2.25 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_rename_is_teacher_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='batch',
        ),
        migrations.AddField(
            model_name='department',
            name='b1',
            field=models.BooleanField(default=False, verbose_name='1styr'),
        ),
        migrations.AddField(
            model_name='department',
            name='b2',
            field=models.BooleanField(default=False, verbose_name='2styr'),
        ),
        migrations.AddField(
            model_name='department',
            name='b3',
            field=models.BooleanField(default=False, verbose_name='3rdyr'),
        ),
    ]
