# Generated by Django 3.2.25 on 2024-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_auto_20240526_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_supersuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
